/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodingSnippetsRouteImport } from './routes/coding-snippets'
import { Route as CuriosityQuestRouteImport } from './routes/curiosity-quest'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LogicPuzzlesRouteImport } from './routes/logic-puzzles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MindfulnessTasksRouteImport } from './routes/mindfulness-tasks'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryDateRouteImport } from './routes/history/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingSnippetsRoute = CodingSnippetsRouteImport.update({
  id: '/coding-snippets',
  path: '/coding-snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const CuriosityQuestRoute = CuriosityQuestRouteImport.update({
  id: '/curiosity-quest',
  path: '/curiosity-quest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicPuzzlesRoute = LogicPuzzlesRouteImport.update({
  id: '/logic-puzzles',
  path: '/logic-puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessTasksRoute = MindfulnessTasksRouteImport.update({
  id: '/mindfulness-tasks',
  path: '/mindfulness-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryDateRoute = HistoryDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coding-snippets': typeof CodingSnippetsRoute
  '/curiosity-quest': typeof CuriosityQuestRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRouteWithChildren
  '/logic-puzzles': typeof LogicPuzzlesRoute
  '/login': typeof LoginRoute
  '/mindfulness-tasks': typeof MindfulnessTasksRoute
  '/history/$date': typeof HistoryDateRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coding-snippets': typeof CodingSnippetsRoute
  '/curiosity-quest': typeof CuriosityQuestRoute
  '/dashboard': typeof DashboardRoute
  '/logic-puzzles': typeof LogicPuzzlesRoute
  '/login': typeof LoginRoute
  '/mindfulness-tasks': typeof MindfulnessTasksRoute
  '/history/$date': typeof HistoryDateRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coding-snippets': typeof CodingSnippetsRoute
  '/curiosity-quest': typeof CuriosityQuestRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRouteWithChildren
  '/logic-puzzles': typeof LogicPuzzlesRoute
  '/login': typeof LoginRoute
  '/mindfulness-tasks': typeof MindfulnessTasksRoute
  '/history/$date': typeof HistoryDateRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coding-snippets'
    | '/curiosity-quest'
    | '/dashboard'
    | '/history'
    | '/logic-puzzles'
    | '/login'
    | '/mindfulness-tasks'
    | '/history/$date'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coding-snippets'
    | '/curiosity-quest'
    | '/dashboard'
    | '/logic-puzzles'
    | '/login'
    | '/mindfulness-tasks'
    | '/history/$date'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/coding-snippets'
    | '/curiosity-quest'
    | '/dashboard'
    | '/history'
    | '/logic-puzzles'
    | '/login'
    | '/mindfulness-tasks'
    | '/history/$date'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodingSnippetsRoute: typeof CodingSnippetsRoute
  CuriosityQuestRoute: typeof CuriosityQuestRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LogicPuzzlesRoute: typeof LogicPuzzlesRoute
  LoginRoute: typeof LoginRoute
  MindfulnessTasksRoute: typeof MindfulnessTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-snippets': {
      id: '/coding-snippets'
      path: '/coding-snippets'
      fullPath: '/coding-snippets'
      preLoaderRoute: typeof CodingSnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curiosity-quest': {
      id: '/curiosity-quest'
      path: '/curiosity-quest'
      fullPath: '/curiosity-quest'
      preLoaderRoute: typeof CuriosityQuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logic-puzzles': {
      id: '/logic-puzzles'
      path: '/logic-puzzles'
      fullPath: '/logic-puzzles'
      preLoaderRoute: typeof LogicPuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness-tasks': {
      id: '/mindfulness-tasks'
      path: '/mindfulness-tasks'
      fullPath: '/mindfulness-tasks'
      preLoaderRoute: typeof MindfulnessTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$date': {
      id: '/history/$date'
      path: '/$date'
      fullPath: '/history/$date'
      preLoaderRoute: typeof HistoryDateRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryDateRoute: typeof HistoryDateRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryDateRoute: HistoryDateRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodingSnippetsRoute: CodingSnippetsRoute,
  CuriosityQuestRoute: CuriosityQuestRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LogicPuzzlesRoute: LogicPuzzlesRoute,
  LoginRoute: LoginRoute,
  MindfulnessTasksRoute: MindfulnessTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
